### ISSUE TITLE
Idea: multiple templates, target loops

### ISSUE THREAD

**Issue by nsheff** [databio/markmeld#1]
I've thought about how markmeld could be used to produce a bunch of PDFs for a mail merge or something. In the past I've done it just by having a separate target for each letter, but then I have to build each separately, or put them all into a pre-build for a mega-target or something.

It would be more convenient if one target could produce multiple outputs, particularly if those outputs are highly similar. Two use cases for this type of function would be 1) mail merge; 2) static site generator. What if targets could have multiple templates, with multiple output files, and the command just ran for each of them? 

## Case 1: mail merge
So maybe something like:

```
targets:
  build_letters:
    output_file: '{person}.pdf'
    outputs:
      - data_variables:
        person: person1
```

Here we don't need to specify an output file for each person, but each person *does* get an individual output file, it's just populated by the `person` variable value.

## Case 2: static site generator

You could basically use this to implement a static site generator...

```
targets:
  build_letters:
    outputs:
      - index.html:
          md_template: index.jinja
          output_file: "index.html"
      - people.html:
          md_template: people.jinja
          output_file: "people.html"
```

For the mail merge, the md_template doesn't need to be included because it's the same for each output. For the static site generator case, different templates and output files are included in each element of the `outputs` attribute. Maybe the output file could be kept as `{output_file}` and then you'd use a data variable to specify it, or something.

## Case 3: only read large data in once for web updates

This could also solve the problem of updating multiple literature threads, while reading in large data only once. Because it's just 1 target, it only has to load the data a single time. I guess this is basically the 'static site generator' use case, just a specific example where it makes sense.

## Implementation

All I need to add is a loop that goes through each element in `output`, updates the main structured data object, and then runs the command. The generic case would be unchanged, really... if no outputs are specified, then a single output is expected with the main data object, no 'outputs update' required.

I think it could use the same functionality as the way a 'target' data package updates a 'general' data package... we'd just copy the 'target' data package and then loop through the build, updating it with each 'output' data package.

**Comment by nsheff** [comment]
better yet, specify the data with an array variable. Add the `loop` section to a `target`:
```
loop:
  loop_data: people
  assign_to: person
```

And then provide the array somehow (through a `data_variable` or through a `data_md` or something)

```
people:
  - person1
  - person2
  - person3
...
```

Now the code would make available the `person1` attributes under `person` to both the templated strings (like `output_file`) and the jinja templates, and execute one command for each array element.

**Comment by nsheff** [comment]
What does this look like for a static site generator?

```
loop:
  loop_data: pages
  assign_to: page

pages:
  - about:
    output_file: _site/about.html
  - home:
    ...
```

But this requires enumerating every page.
