### ISSUE TITLE
Target relativity

### ISSUE THREAD

**Issue by nsheff** [databio/markmeld#5]
In 83c0ca0dc9098f5c368939dce388e15294ee7f65 I made it so a command would be executed in the CWD relative to the markmeld file in which the target was defined. 

I can't remember the use case, but I wanted to build figures or something that would be relative to a markmeld file, and then import those targets in a different file, but be able to call them from that other directory.

The problem is that I *also* sometimes want to define a target in a global config, and then use it and have it be relative to the import*ing* markmeld file.

So, you can't have it both ways... the targets have to either execute relative to the imported or importing file. 

Possible solutions:

- I guess `imports` could have a relativity argument... so it would be:

```
imports:
     - path: /path/to/file.yaml
       relative: true
    - path: /path/to/other/file.yaml
      relative: false
```

This would allow relativity to be controlled at the per-import level. Or:

```
relative_imports:
- one
- two
- three
imports:
- four
- five
- size
```
