### ISSUE TITLE
streamline data source specification

### ISSUE THREAD

**Issue by nsheff** [databio/markmeld#6]
I just added in a new configuration option called `'data_yaml_keyed`. This allows you to specify yaml data (as files) that live under keys so they can be accessed via keys from jinja.

In the process I think this has risen to a level of complication that makes it worth rethinking the way the user can do these things. There's:

- keyed yaml
- keyed markdown
- markdown file globs
- yaml files (is it globs?)
- data variables

I can make all these things more parallel in presentation to try to simplify config management for the user.

**Comment by nsheff** [comment]
In parallel now, possible content keys are

- `data_md_globs` - filepaths to filename-indexed md
- `data_yaml_globs` - filepaths to filename-indexed yaml
- `data_md_files` - paths to md files, loaded into keys provided
- `data_yaml_files` - keyed paths to yaml files, loaded in directly
- `data_variables` - content supplied directly in the config yaml

But version 2 provides a different way to encode this, which uses `md` and `yaml` keys, like:

```
  test_data_variables:
    jinja_template: variables_test.jinja
    data:
      md:
        some_text_data: some_text.md
        file2: md_files/file3.md
      md_globs:
        - "md_files/*.md"
      yaml:
        key1: file1.yaml
      yaml_globs:
        - "files/*.yaml"
      variables:
        x: 6s0BoZEiiN
```

this is a more parallel naming scheme. but it doesn't provide the ability to give yaml data that will be included directly anymore -- it all must be under a key specified in the markmeld.cfg.

Do I want yaml to be able to be inserted directly? It would make markmeld more flexible to re-using existing templates. But, it would make there be multiple ways to do things, which can be confusing.
